language: java
jdk:
  - oraclejdk8
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: rameshuser123@gmail.com
  password: Tango@123
  organization: SaganCoreTest
  space: Sagan_Core
  on:
    branch: master

  
      
   

