language: java
os:
  - windows

deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: sourabh_bhorjare@persistent.co.in
  password: Ruchika@12
  organization: sourabh_bhorjare
  space: prod
  on:
    branch: master
language: sh
after_script:
   - sh abc.sh
 
  
      
   

