language: java
os:
  - windows
env:
  - NODE_ENV=production
  - NODE_ENV=staging
  
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    slack:
      on_success: always
  irc: "chat.freenode.net#my-channel"
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: sourabh_bhorjare@persistent.co.in
  password: Ruchika@12
  organization: sourabh_bhorjare
  space: prod
  on:
    branch: master
language: sh
after_script:
   - sh abc.sh
 
  
      
   

