language: java
os:
  - windows
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    slack:
      on_success: always
  irc: "chat.freenode.net#my-channel"
language: sh
after_script:
   - sh abc.sh
 
  
      
   

