language: java
jdk:
  - oraclejdk8
os:
  - windows
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: sourabh_bhorjare@persistent.co.in
  password: Ruchika@12
  organization: sourabh_bhorjare
  space: Sagantest
  on:
    branch: master

  
      
   

